apiVersion: v1
kind: Service
metadata:
  name: blackjack-service
  labels:
    app: blackjack
spec:
  selector:
    app: blackjack
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer